name = "PAUSED"
default_targets = ["win32", "win64", "macos", "lovejs"]
build_directory = "makelove-build"

love_files = [
    "+*",
    "-*/.*",
    "-./makelove-build/*",
    "-./aseprite/*",
    "-./res/ldtk/game/backups/*"
]

icon_file = "icon.png"

[windows]
[windows.exe_metadata]
FileDescription = "Help a cute duckling with his bunny friend go home."
FileVersion = "0.1"
CompanyName = "A game by Hamdy Elzonqali."
LegalCopyright = "Copyright © 2023 CYFO GAMES"
ProductName = "PAUSED" # "LÖVE"
ProductVersion = "0.1"
OriginalFilename = "PAUSED.exe"

[macos]
[macos.app_metadata]
CFBundleName = "PAUSED"
CFBundleIdentifier = "com.cyfo.paused"
NSHumanReadableCopyright = "Copyright © 2023 CYFO GAMES"
CFBundleShortVersionString = "0.1"

[linux]
[linux.desktop_file_metadata]
Comment="Help a cute duckling with his bunny friend go home."
Categories="Game;"

[lovejs]
title = "PAUSED"
