name: Pull Request Check

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'tools/**'
    branches:
      - main

concurrency: 
  group: release # only 1 anything at a time

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: hmarr/debug-action@v2
        name: "debug: ${{github.event_name}}"

      - name: Check Port Files
        id: ports-info
        run: |
          ~/git-scripts/PortMaster-New-PR-Check.sh "${{ github.event.pull_request.number }}"
